export const LIST_SUBCOMPANIES = 'LIST_SUBCOMPANIES'
export const ADD_SUBCOMPANY = 'ADD_SUBCOMPANY'
export const UPDATE_SUBCOMPANY = 'UPDATE_SUBCOMPANY'
export const DELETE_SUBCOMPANY = 'DELETE_SUBCOMPANY'
